rebrickable:
  key: insert-key

spring:
  server.tomcat:
    connection-timeout: 600000
  graphql:
    graphiql:
      enabled: true
  datasource:
    #https://www.baeldung.com/spring-boot-h2-database
    url: jdbc:h2:file:./h2-bricks;AUTO_SERVER=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    show-sql: false
    database-platform: org.hibernate.dialect.H2Dialect
    #    properties:
    #      hibernate.cache.use_second_level_cache: true
    #      hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
    hibernate:
      ddl-auto: update
      format_sql: true
      initialization-mode: always
    #    schema: initial-schema.sql
    #    data: initial-data.sql
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        temp:
          use_jdbc_metadata_defaults: false
          event:
            merge:
              entity_copy_observer: allow

  h2:
    #Starts the Web Console at http://localhost:8080/h2-console
    console.enabled: true

  jackson:
    default-property-inclusion: NON_EMPTY
    serialization:
      write-dates-as-timestamps: false
      indent_output: true